Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance.
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fca0f98dc87d39df
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: |
            #!/bin/bash
            sudo yum update -y
            sudo yum install git -y
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./kubectl
            chmod +x ./aws-iam-authenticator
            sudo mv ./kubectl /usr/local/bin/kubectl && export PATH=$PATH:/usr/local/bin
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator && export PATH=$PATH:/usr/local/bin
            echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc
            sudo amazon-linux-extras install epel -y
            sudo yum install tidy -y
            sudo yum install docker -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo gpasswd -a $USER docker
            sudo systemctl restart docker
            sudo chmod 766 /var/run/docker.sock
            sudo wget -O /etc/yum.repos.d/jenkins.repo \
                https://pkg.jenkins.io/redhat-stable/jenkins.repo
            sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
            sudo yum upgrade -y
            sudo yum install jenkins java-1.8.0-openjdk-devel -y
            sudo systemctl daemon-reload
            sudo systemctl start jenkins


  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP + SSH + jenkins 8080"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: !Ref SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      - CidrIp: !Ref SSHLocation
        FromPort: '8080'
        IpProtocol: tcp
        ToPort: '8080'

